from enum import Enum, unique, auto

"""
Symbology --- Describes barcode type.

@author Dbuhrsmith@zebra.com

"""

@unique
class Symbology(Enum):
	auspost = auto()
	azteccode = auto()
	azteccodecompact = auto()
	aztecrune = auto()
	bc412 = auto()
	channelcode = auto()
	codablockf = auto()
	code11 = auto()
	code128 = auto()
	code16k = auto()
	code2of5 = auto()
	code32 = auto()
	code39 = auto()
	code39ext = auto()
	code49 = auto()
	code93 = auto()
	code93ext = auto()
	codeone = auto()
	coop2of5 = auto()
	daft = auto()
	databarexpanded = auto()
	databarexpandedcomposite = auto()
	databarexpandedstacked = auto()
	databarexpandedstackedcomposite = auto()
	databarlimited = auto()
	databarlimitedcomposite = auto()
	databaromni = auto()
	databaromnicomposite = auto()
	databarstacked = auto()
	databarstackedcomposite = auto()
	databarstackedomni = auto()
	databarstackedomnicomposite = auto()
	databartruncated = auto()
	databartruncatedcomposite = auto()
	datalogic2of5 = auto()
	datamatrix = auto()
	datamatrixrectangular = auto()
	dotcode = auto()
	ean13 = auto()
	ean13composite = auto()
	ean14 = auto()
	ean2 = auto()
	ean5 = auto()
	ean8 = auto()
	ean8composite = auto()
	flattermarken = auto()
	gs1_128 = auto()
	gs1_128composite = auto()
	gs1_cc = auto()
	gs1datamatrix = auto()
	gs1datamatrixrectangular = auto()
	gs1northamericancoupon = auto()
	gs1qrcode = auto()
	hanxin = auto()
	hibcazteccode = auto()
	hibccodablockf = auto()
	hibccode128 = auto()
	hibccode39 = auto()
	hibcdatamatrix = auto()
	hibcdatamatrixrectangular = auto()
	hibcmicropdf417 = auto()
	hibcpdf417 = auto()
	hibcqrcode = auto()
	iata2of5 = auto()
	identcode = auto()
	industrial2of5 = auto()
	interleaved2of5 = auto()
	isbn = auto()
	ismn = auto()
	issn = auto()
	itf14 = auto()
	japanpost = auto()
	kix = auto()
	leitcode = auto()
	matrix2of5 = auto()
	maxicode = auto()
	micropdf417 = auto()
	microqrcode = auto()
	msi = auto()
	onecode = auto()
	pdf417 = auto()
	pdf417compact = auto()
	pharmacode2 = auto()
	pharmacode = auto()
	planet = auto()
	plessey = auto()
	posicode = auto()
	postnet = auto()
	pzn = auto()
	qrcode = auto()
	rationalizedCodabar = auto()
	raw = auto()
	royalmail = auto()
	sscc18 = auto()
	symbol = auto()
	telepen = auto()
	telepennumeric = auto()
	ultracode = auto()
	upca = auto()
	upcacomposite = auto()
	upce = auto()
	upcecomposite = auto()

	def toString():
		return super.toString().replace('_', '-')

	@staticmethod
	def fromString(symbology):
			return Symbology.value(symbology.replace('-', '_'))